
SET APACHE_JMETER_HOME=C:\IBM\apache-jmeter-2.13
SET JMETER_HOME=%APACHE_JMETER_HOME%\bin
SET TEST_PLAN_HOME=%APACHE_JMETER_HOME%\ibm\testcases
SET TEST_PLAN_TEMPLATE=Lombardi_Production_Benchmark-v8.5.0.jmx